// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Adicionar ao carrinho', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Adicionar ao carrinho', async function() {
    // Test name: Adicionar ao carrinho
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3001/")
    // 2 | setWindowSize | 1936x1048 | 
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    // 3 | click | css=.bg-white:nth-child(3) .rounded-full:nth-child(2) > .text-gray-600 | 
    await driver.findElement(By.css(".bg-white:nth-child(3) .rounded-full:nth-child(2) > .text-gray-600")).click()
  })
})
