// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Entrar em categoria', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Entrar em categoria', async function() {
    // Test name: Entrar em categoria
    // Step # | name | target | value
    // 1 | open | /eac0b83f-4c81-44ef-b79e-82672c0816cd | 
    await driver.get("http://localhost:3001/eac0b83f-4c81-44ef-b79e-82672c0816cd")
    // 2 | setWindowSize | 1936x1048 | 
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    // 3 | click | linkText=Loja | 
    await driver.findElement(By.linkText("Loja")).click()
    // 4 | click | linkText=Elétrica | 
    await driver.findElement(By.linkText("Elétrica")).click()
  })
})
