// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Excluir categoria', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Excluir categoria', async function() {
    // Test name: Excluir categoria
    // Step # | name | target | value
    // 1 | open | /eac0b83f-4c81-44ef-b79e-82672c0816cd | 
    await driver.get("http://localhost:3001/eac0b83f-4c81-44ef-b79e-82672c0816cd")
    // 2 | setWindowSize | 1936x1048 | 
    await driver.manage().window().setRect({ width: 1936, height: 1048 })
    // 3 | click | linkText=Categorias | 
    await driver.findElement(By.linkText("Categorias")).click()
    // 4 | mouseOver | css=#radix-\3Arc\3A > .h-4 | 
    {
      const element = await driver.findElement(By.css("#radix-\\3Arc\\3A > .h-4"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | mouseOut | css=#radix-\3Arc\3A > .h-4 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 6 | click | css=html | 
    await driver.findElement(By.css("html")).click()
    // 7 | click | css=.relative:nth-child(4) | 
    await driver.findElement(By.css(".relative:nth-child(4)")).click()
    // 8 | click | css=.hover\3A bg-destructive\/90 | 
    await driver.findElement(By.css(".hover\\3A bg-destructive\\/90")).click()
  })
})
